import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { nav } from "@/components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <html lang="en" className="font-sans bg-slate-100 text-slate-900 dark:bg-slate-900 dark:text-slate-100 ">
        <body className={`flex flex-col justify-center`}>
            <nav.Navbar />
            { children }
            <nav.Footer />
        </body>
    </html>
}
